### ISSUE TITLE
Consider implementing error for KeyError

### ISSUE THREAD

**Issue by Connor1996** [pingcap-incubator/tinykv#134]
just like how `RegionError` does, we can implement error for `kvrpcpb.KeyError` like this:
```go 
type KeyError struct {
	Err *kvrpcpb.KeyError
}

func (ke *KeyError) Error() string {
	return ke.Err.String()
}
```
so function can unify return value of `kvrpcpb.KeyError` into `error`. For example 
```go
func (p *Prewrite) prewriteMutation(txn *mvcc.MvccTxn, mut *kvrpcpb.Mutation) (*kvrpcpb.KeyError, error)  {}
->
func (p *Prewrite) prewriteMutation(txn *mvcc.MvccTxn, mut *kvrpcpb.Mutation) error {}
```

```go
func (scan *Scanner) Next() ([]byte, []byte, interface{}) {}
-> 
func (scan *Scanner) Next() ([]byte, []byte, error) {}
```

**Comment by Connor1996** [comment]
PTAL @nrc

**Comment by nrc** [comment]
I looked at all uses of `KeyError`, and I think that `Scanner::Next` is the only place this change would help, and there all it does is change the signature from `interface{}` to `error`. Most uses just write the `KeyError` into a response. The `prewriteMutation` case would probably make the code worse because the caller would have to check the type of the returned error and do different things depending on if it is a `KeyError` or something else.

From a design point of view, a `KeyError` is not an `error` in the sense of the Go interface since it does not represent some kind of 'bad' behaviour, but rather TinyKV executing as expected and finding an application error.

**Comment by Connor1996** [comment]
But when implementing coprocessor, which use `Scanner::Next`. It would introduce `interface{}` all the way of coprocessor.

> The prewriteMutation case would probably make the code worse because the caller would have to check the type of the returned error and do different things depending on if it is a KeyError or something else.

After this PR https://github.com/pingcap-incubator/tinykv/pull/139, seems we just need to change `regionError()` to something like this 
```go
func bindError(err error, resp interface{}) (interface{}, error) {
        if regionError, ok := err.(*raft_storage.RegionError); ok {
		respValue := reflect.ValueOf(resp)
		respValue.FieldByName("RegionError").Set(reflect.ValueOf(regionError.RequestErr))
		return resp, nil
	}
        if keyError, ok := err.(*transaction.KeyError); ok {
		respValue := reflect.ValueOf(resp)
		respValue.FieldByName("KeyError").Set(reflect.ValueOf(keyError.RequestErr))
		return resp, nil
	}
        return nil, err
}

**Comment by nrc** [comment]
> After this PR #139, seems we just need to change regionError() to something like this

This doesn't work because `prewriteMutation` creates `Conflict` message if there is a key error, rather than just storing the error in a `KeyError` field.

> But when implementing coprocessor, which use Scanner::Next. It would introduce interface{} all the way of coprocessor.

I see, that seems sub-optimal, I'll take another look...
